FROM projectatomic/atomicapp:0.4.4

MAINTAINER Your Name <email@example.com>

LABEL io.projectatomic.nulecule.specversion 0.1.0
LABEL io.projectatomic.nulecule.providers = "provider1,provider2"

ADD /Nulecule /Dockerfile /application-entity/
ADD /artifacts /application-entity/artifacts
