FROM projectatomic/atomicapp:dev

MAINTAINER Christoph Görn <goern@redhat.com>

ADD /nulecule /Dockerfile README.asciidoc gpl-3.0.txt /application-entity/
ADD /artifacts /application-entity/artifacts
