FROM projectatomic/atomicapp:0.1.0

MAINTAINER Christoph Görn <goern@redhat.com>

LABEL io.projectatomic.nulecule.specversion 0.0.1-alpha

LABEL Build docker build --rm --tag goern/mysql-centos7-atomicapp .


ADD /Nulecule /Dockerfile README.asciidoc gpl-3.0.txt /application-entity/
ADD /artifacts /application-entity/artifacts
