FROM scratch

RUN mkdir /application-entity
WORKDIR /application-entity
ADD Atomicfile /application-entity/Atomicfile
ADD Dockerfile /application-entity/Dockerfile
ADD params.conf /application-entity/params.conf
ADD graph/ /application-entity/graph/
