FROM projectatomic/atomicapp:0.1.3

MAINTAINER Christoph Görn <goern@redhat.com>

LABEL io.projectatomic.nulecule.specversion="0.0.2" \
      io.projectatomic.nulecule.providers="kubernetes,docker,openshift"

ADD /Nulecule gpl-3.0.txt /application-entity/
ADD /artifacts /application-entity/artifacts
