FROM projectatomic/atomicapp:0.1.0

MAINTAINER langdon <langdon@fedoraproject.org>

LABEL io.projectatomic.nulecule.specversion 0.0.1-alpha

LABEL Build docker build --rm --tag testing/skydns-atomicapp .


ADD Nulecule /application-entity/
ADD artifacts/ /application-entity/artifacts/
