app_template_version: v1-alpha

description: This is CSS on top of Wordpress

parameters:
  ip_addr:
    description: The ip of the host the application will be deployed on
  image:
    description: Runtime binary docker image, ex. docker://user/myapp
    default: user/custom_wpapp

resources:
  myapp:
    type: kubernetes::metadata
    depends_on: mariadb
    properties:
      public_ip: { get_param: ip_addr }
      image: { get_param: image }
      deploy:
        - template: {get_file: k8s/pod.json}
          params:
            $IMAGE: {get_param: image}
        - get_file: k8s/service.json
        - get_file: k8s/replication_controller.json
  mariadb:
    "kubernetes::metadata": docker://maria/db:app-1.0.0
    properties:
      params:
        $REPLICAS: {get_param: replicas}

