FROM projectatomic/atomicapp:0.1.1

MAINTAINER langdon <langdon@fedoraproject.org>

LABEL io.projectatomic.nulecule.providers = "kubernetes,docker"
LABEL io.projectatomic.nulecule.specversion 0.0.2

ADD Nulecule /application-entity/
ADD graph/ /application-entity/graph/
